In [6]:
%pylab inline
%matplotlib inline
import gsw
import netCDF4 as nc
import xarray as xr 
import pylab as plt
import scipy.io
import math
import numpy.matlib
import xlrd
import pandas as pd
from scipy import stats 
import seaborn as sns
import cartopy
import cartopy.crs as ccrs

Populating the interactive namespace from numpy and matplotlib


In [15]:
data_path = '~/Users/atang/Documents/PhD_Internship/Python/Tommy Data/'


In [19]:
ctd_ts_data = pd.read_csv('/Users/atang/Documents/PhD_Internship/Python/Tommy Data/ctd_ts_data.csv')
ctd_fe_data_0 = pd.read_csv('/Users/atang/Documents/PhD_Internship/Python/Tommy Data/ctd_fe_data_0.csv')

In [17]:
pwd

'C:\\Users\\atang\\Documents\\PhD_Internship\\Python\\Tommy Data'

In [21]:
density_ts_data = gsw.density.rho(ctd_ts_data['sal'].values,ctd_ts_data['temp'].values,ctd_ts_data['depth'].values)-1000

In [25]:
density_ts_data

array([27.17695626, 27.18447247, 27.18957026, ..., 34.16196033,
       34.16328217, 34.16971083])

In [28]:
ctd_ts_data['Density'] = density_ts_data
ctd_ts_data

datetime   ctd  Longitude   Latitude     depth    temp  \
0      06/07/2017 03:37  TM01   30.00000 -58.500833     0.999  0.0401   
1      06/07/2017 03:37  TM01   30.00000 -58.500833     1.967 -0.0597   
2      06/07/2017 03:37  TM01   30.00000 -58.500833     2.956 -0.0656   
3      06/07/2017 03:37  TM01   30.00000 -58.500833     3.984 -0.0638   
4      06/07/2017 03:37  TM01   30.00000 -58.500833     4.954 -0.0601   
...                 ...   ...        ...        ...       ...     ...   
20018  10/07/2017 20:20  TM08   29.99967 -41.000167  1483.031  3.4867   
20019  10/07/2017 20:20  TM08   29.99967 -41.000167  1484.016  3.4845   
20020  10/07/2017 20:20  TM08   29.99967 -41.000167  1484.997  3.4888   
20021  10/07/2017 20:20  TM08   29.99967 -41.000167  1485.986  3.5004   
20022  10/07/2017 20:20  TM08   29.99967 -41.000167  1486.979  3.4930   

           sal    oxy      chl  pressure    Density  
0      34.0029  7.434  0.19132         1  27.176956  
1      34.0002  7.437  0.18135         2  27.184472  
2      34.0003  7.446  0.17786         3  27.189570  
3      34.0000  7.440  0.17640         4  27.194148  
4      34.0005  7.432  0.20149         5  27.198995  
...        ...    ...      ...       ...        ...  
20018  34.5407  3.560  0.00495      1500  34.152903  
20019  34.5417  3.560  0.00508      1501  34.158430  
20020  34.5413  3.564  0.00769      1502  34.161960  
20021  34.5393  3.564  0.00737      1503  34.163282  
20022  34.5405  3.561 -0.00006      1504  34.169711  

[20023 rows x 11 columns]

In [31]:
#creating a reference density at 10m
density_mld_reference_10m = density_ts_data[9]
density_mld_reference_10m

27.222598050942906

mixed_layer_depth_dens = density_ts_data-density_mld_reference_10m

In [34]:
mixed_layer_depth_dens = density_ts_data-density_mld_reference_10m
mixed_layer_depth_dens

array([-0.04564179, -0.03812558, -0.03302779, ...,  6.93936228,
        6.94068411,  6.94711278])

In [37]:
a = mixed_layer_depth_dens<0.031
a

array([ True,  True,  True, ..., False, False, False])

In [43]:
max_value = np.max(mixed_layer_depth_dens)
index_max_value = np.where(mixed_layer_depth_dens==max_value)
max_value
index_max_value

(array([12758], dtype=int64),)

In [45]:
ctd_ts_data.depth[12758]



4179.438